# Generated by Django 3.2 on 2021-04-28 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'order_status',
            },
        ),
        migrations.CreateModel(
            name='ShipmentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'shipment_informations',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
