# Generated by Django 3.2 on 2021-04-28 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthgoal',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.option'),
        ),
        migrations.AddField(
            model_name='healthgoal',
            name='product',
            field=models.ManyToManyField(through='products.ProductHealthGoal', to='products.Product'),
        ),
    ]
