# Generated by Django 3.2 on 2021-04-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthgoal',
            name='product',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='heath_goal',
            field=models.ManyToManyField(through='products.ProductHealthGoal', to='products.HealthGoal'),
        ),
        migrations.AddField(
            model_name='product',
            name='symbol',
            field=models.ManyToManyField(through='products.ProductSymbol', to='products.Symbol'),
        ),
    ]
